[project]
name = "gemini-fastapi"
version = "1.0.0"
description = "FastAPI Server built on Gemini Web API"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "fastapi>=0.115.12",
    # Use the fork with streaming support. Install directly from the GitHub repo
    # and keep the import package name as `gemini_webapi` so code imports remain
    # unchanged.
    "gemini_webapi @ git+https://github.com/hvjg2578/Gemini-API.git@52684cea8f0caac6206ac691b90113fce966fe43",
    "lmdb>=1.6.2",
    "loguru>=0.7.0",
    "pydantic-settings[yaml]>=2.9.1",
    "uvicorn>=0.34.1",
    "uvloop>=0.21.0; sys_platform != 'win32'",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.11.7",
]

[tool.ruff]
line-length = 100
lint.select = ["E", "F", "W", "I", "RUF"]
lint.ignore = ["E501"] 

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
